import { Component, TextFile, github, typescript } from 'projen';

/**
 * One path-scoped allowlist entry for the generated `.gitleaks.toml`.
 *
 * Each entry is rendered as a `[[allowlists]]` block. Keep every allowlist as
 * tightly path-scoped as possible so it cannot mask a real secret elsewhere in
 * the repo.
 */
export interface GitleaksAllowlist {
  /** Human-readable description of what this allowlist exempts and why. */
  readonly description: string;
  /**
   * Regex paths the allowlist applies to (rendered as gitleaks `paths`), e.g.
   * `['^\\.npmrc$']`. Omit to apply the regexes repo-wide (discouraged).
   *
   * @default - no path scope
   */
  readonly paths?: string[];
  /**
   * Regexes matching the allowed secret values (rendered as gitleaks
   * `regexes`). Omit to allow anything on the scoped paths.
   *
   * @default - no value regexes
   */
  readonly regexes?: string[];
  /**
   * gitleaks `condition` combining `paths` and `regexes` (`AND` requires both).
   *
   * @default - gitleaks default (OR)
   */
  readonly condition?: string;
  /**
   * gitleaks `regexTarget` (`secret` | `match` | `line`).
   *
   * @default - gitleaks default
   */
  readonly regexTarget?: string;
}

export interface GitleaksOptions {
  /**
   * The gitleaks version downloaded in CI.
   *
   * @default '8.30.1'
   */
  readonly version?: string;
  /**
   * Path-scoped allowlists for known false positives, appended after
   * `[extend] useDefault = true`.
   *
   * @default []
   */
  readonly allowlists?: GitleaksAllowlist[];
}

/**
 * gitleaks secret-scanning for a project: a `.gitleaks.toml` config that extends
 * the bundled default ruleset plus tightly path-scoped allowlists, and a
 * pull-request workflow that scans the full git history against it.
 *
 * projen has no native gitleaks component, so both artifacts are generated here
 * to stay in the "never hand-edit generated files" model. Requires GitHub to be
 * enabled on the project.
 */
export class Gitleaks extends Component {

  /** The generated `.gitleaks.toml`. */
  public readonly configFile: TextFile;

  /** The generated pull-request scanning workflow. */
  public readonly workflow: github.GithubWorkflow;

  constructor(scope: typescript.TypeScriptProject, options: GitleaksOptions = {}) {
    super(scope);

    if (!scope.github) {
      throw new Error('Gitleaks requires GitHub to be enabled on the project');
    }

    const version = options.version ?? '8.30.1';
    const allowlists = options.allowlists ?? [];

    const lines: string[] = [
      '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
      '#',
      '# gitleaks config. Extends the default ruleset, then adds tightly scoped',
      '# allowlists for known false positives. Each allowlist is path-scoped so it',
      '# cannot mask a real secret elsewhere in the repo.',
      '[extend]',
      'useDefault = true',
    ];
    for (const a of allowlists) {
      lines.push('', `# ${a.description}`, '[[allowlists]]', `description = ${JSON.stringify(a.description)}`);
      if (a.condition) {
        lines.push(`condition = ${JSON.stringify(a.condition)}`);
      }
      if (a.regexTarget) {
        lines.push(`regexTarget = ${JSON.stringify(a.regexTarget)}`);
      }
      if (a.paths && a.paths.length > 0) {
        lines.push(`paths = [${a.paths.map((p) => `'''${p}'''`).join(', ')}]`);
      }
      if (a.regexes && a.regexes.length > 0) {
        lines.push(`regexes = [${a.regexes.map((r) => `'''${r}'''`).join(', ')}]`);
      }
    }

    this.configFile = new TextFile(scope, '.gitleaks.toml', {
      lines,
      // A `//`-style projen marker is invalid TOML; the `#` marker is baked in.
      marker: false,
    });

    this.workflow = scope.github.addWorkflow('gitleaks');
    // Secrets can land in any path, so no path filter — plus merge queue and
    // manual dispatch, matching the repo's other workflows.
    this.workflow.on({
      pullRequest: {},
      mergeGroup: {},
      workflowDispatch: {},
    });
    this.workflow.addJob('gitleaks', {
      runsOn: ['ubuntu-latest'],
      permissions: { contents: github.workflows.JobPermission.READ },
      steps: [
        {
          name: 'Checkout',
          uses: 'actions/checkout@v4',
          // Full history so gitleaks scans every commit in the PR, not just HEAD.
          with: { 'fetch-depth': 0 },
        },
        {
          name: 'Install gitleaks',
          run: [
            `curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v${version}/gitleaks_${version}_linux_x64.tar.gz \\`,
            '  | tar -xz gitleaks',
            'sudo mv gitleaks /usr/local/bin/gitleaks',
          ].join('\n'),
        },
        {
          name: 'Scan git history',
          // --redact keeps any real secret out of the public CI logs.
          run: 'gitleaks git --no-banner --redact .',
        },
      ],
    });
  }
}
